### PR TITLE
LineProfile : express distance from start of line in percentage.

### PR DESCRIPTION
**Pull request by chir-set**
Show percent distance along line from start.

This may decrease measurement steps to calculate the importance of an arterial stenosis.

(Though not all types of stenosis are concerned here, namely, concentric stenosis.)

### CODE REVIEW

**Review by lassoan — COMMENTED** [review]
Thank you, this can be useful.

Please update the code so that you don't hijack the existing DISTANCE_ARRAY column for two different purposes, but add a new RELATIVE_DISTANCE_ARRAY column (to keep the logic simple and keep modules that use this logic simple). So, logic.updateOutputTable would compute all the columns. You can still keep the checkbox to choose between absolute and relative distance for plotting (just move the checkbox near the plotting or make it clear in the name or tooltip).

You could also find SegmentCrossSectionArea module relevant. You can use that to compute cross-sectional area of the vessel based on the volume straightened by CurvedPlanarReformat.

**Comment by chir-set** [comment]
> So, logic.updateOutputTable would compute all the columns

This part is done.

> move the checkbox near the plotting or make it clear in the name or tooltip

I'm afraid I don't fully understand what you mean here, as well as the motivation.

**Comment by lassoan** [comment]
>>move the checkbox near the plotting or make it clear in the name or tooltip
>
> I'm afraid I don't fully understand what you mean here, as well as the motivation.

The checkbox may still be useful for choosing which column to use as X axis in the plot (absolute or relative). It is easy to change the x axis in Plots module, too, so it is also OK to remove the checkbox and always use absolute distance as X axis in plots.

**Comment by chir-set** [comment]
> It is easy to change the x axis in Plots module, too,

You mean, interactively in the Plot widget ? Can't figure out how. I saw there can be multiple 'Plot data series' that are checkable.

Ideally, there could be a second X-axis, one scaled on the absolute distance and the second one on the relative distance. Don't if it's possible.

**Comment by lassoan** [comment]
I've made a few small adjustments and merged. Thanks a lot for your contribution!

**Pull request closed without merging**
